[green_agent]
agentbeats_id = "019bc406-77f9-7a13-9fa6-ea6987e19db3"
env = { }

[[participants]]
agentbeats_id = ""
name = "planner"
env = {}

[config]
# Add your assessment config here
domains = ["barman", "blocksworld",  "childsnack", "gripper"]
easy_count = 1
medium_count = 1
hard_count = 1